/*
 Copyright (c) Huawei Technologies Co., Ltd. 2022-2023. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "huawei-csi-driver/client/apis/xuanwu/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StorageBackendContentLister helps list StorageBackendContents.
// All objects returned here must be treated as read-only.
type StorageBackendContentLister interface {
	// List lists all StorageBackendContents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.StorageBackendContent, err error)
	// Get retrieves the StorageBackendContent from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.StorageBackendContent, error)
	StorageBackendContentListerExpansion
}

// storageBackendContentLister implements the StorageBackendContentLister interface.
type storageBackendContentLister struct {
	indexer cache.Indexer
}

// NewStorageBackendContentLister returns a new StorageBackendContentLister.
func NewStorageBackendContentLister(indexer cache.Indexer) StorageBackendContentLister {
	return &storageBackendContentLister{indexer: indexer}
}

// List lists all StorageBackendContents in the indexer.
func (s *storageBackendContentLister) List(selector labels.Selector) (ret []*v1.StorageBackendContent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.StorageBackendContent))
	})
	return ret, err
}

// Get retrieves the StorageBackendContent from the index for a given name.
func (s *storageBackendContentLister) Get(name string) (*v1.StorageBackendContent, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("storagebackendcontent"), name)
	}
	return obj.(*v1.StorageBackendContent), nil
}
