/*
 Copyright (c) Huawei Technologies Co., Ltd. 2022-2023. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	xuanwuv1 "huawei-csi-driver/client/apis/xuanwu/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageBackendContents implements StorageBackendContentInterface
type FakeStorageBackendContents struct {
	Fake *FakeXuanwuV1
}

var storagebackendcontentsResource = schema.GroupVersionResource{Group: "xuanwu.huawei.io", Version: "v1", Resource: "storagebackendcontents"}

var storagebackendcontentsKind = schema.GroupVersionKind{Group: "xuanwu.huawei.io", Version: "v1", Kind: "StorageBackendContent"}

// Get takes name of the storageBackendContent, and returns the corresponding storageBackendContent object, and an error if there is any.
func (c *FakeStorageBackendContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *xuanwuv1.StorageBackendContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(storagebackendcontentsResource, name), &xuanwuv1.StorageBackendContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.StorageBackendContent), err
}

// List takes label and field selectors, and returns the list of StorageBackendContents that match those selectors.
func (c *FakeStorageBackendContents) List(ctx context.Context, opts v1.ListOptions) (result *xuanwuv1.StorageBackendContentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(storagebackendcontentsResource, storagebackendcontentsKind, opts), &xuanwuv1.StorageBackendContentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &xuanwuv1.StorageBackendContentList{ListMeta: obj.(*xuanwuv1.StorageBackendContentList).ListMeta}
	for _, item := range obj.(*xuanwuv1.StorageBackendContentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageBackendContents.
func (c *FakeStorageBackendContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(storagebackendcontentsResource, opts))
}

// Create takes the representation of a storageBackendContent and creates it.  Returns the server's representation of the storageBackendContent, and an error, if there is any.
func (c *FakeStorageBackendContents) Create(ctx context.Context, storageBackendContent *xuanwuv1.StorageBackendContent, opts v1.CreateOptions) (result *xuanwuv1.StorageBackendContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(storagebackendcontentsResource, storageBackendContent), &xuanwuv1.StorageBackendContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.StorageBackendContent), err
}

// Update takes the representation of a storageBackendContent and updates it. Returns the server's representation of the storageBackendContent, and an error, if there is any.
func (c *FakeStorageBackendContents) Update(ctx context.Context, storageBackendContent *xuanwuv1.StorageBackendContent, opts v1.UpdateOptions) (result *xuanwuv1.StorageBackendContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(storagebackendcontentsResource, storageBackendContent), &xuanwuv1.StorageBackendContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.StorageBackendContent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStorageBackendContents) UpdateStatus(ctx context.Context, storageBackendContent *xuanwuv1.StorageBackendContent, opts v1.UpdateOptions) (*xuanwuv1.StorageBackendContent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(storagebackendcontentsResource, "status", storageBackendContent), &xuanwuv1.StorageBackendContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.StorageBackendContent), err
}

// Delete takes name of the storageBackendContent and deletes it. Returns an error if one occurs.
func (c *FakeStorageBackendContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(storagebackendcontentsResource, name), &xuanwuv1.StorageBackendContent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageBackendContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(storagebackendcontentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &xuanwuv1.StorageBackendContentList{})
	return err
}

// Patch applies the patch and returns the patched storageBackendContent.
func (c *FakeStorageBackendContents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *xuanwuv1.StorageBackendContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(storagebackendcontentsResource, name, pt, data, subresources...), &xuanwuv1.StorageBackendContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.StorageBackendContent), err
}
