/*
 Copyright (c) Huawei Technologies Co., Ltd. 2022-2023. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	xuanwuv1 "huawei-csi-driver/client/apis/xuanwu/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeModifyClaims implements VolumeModifyClaimInterface
type FakeVolumeModifyClaims struct {
	Fake *FakeXuanwuV1
}

var volumemodifyclaimsResource = schema.GroupVersionResource{Group: "xuanwu.huawei.io", Version: "v1", Resource: "volumemodifyclaims"}

var volumemodifyclaimsKind = schema.GroupVersionKind{Group: "xuanwu.huawei.io", Version: "v1", Kind: "VolumeModifyClaim"}

// Get takes name of the volumeModifyClaim, and returns the corresponding volumeModifyClaim object, and an error if there is any.
func (c *FakeVolumeModifyClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *xuanwuv1.VolumeModifyClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(volumemodifyclaimsResource, name), &xuanwuv1.VolumeModifyClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.VolumeModifyClaim), err
}

// List takes label and field selectors, and returns the list of VolumeModifyClaims that match those selectors.
func (c *FakeVolumeModifyClaims) List(ctx context.Context, opts v1.ListOptions) (result *xuanwuv1.VolumeModifyClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(volumemodifyclaimsResource, volumemodifyclaimsKind, opts), &xuanwuv1.VolumeModifyClaimList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &xuanwuv1.VolumeModifyClaimList{ListMeta: obj.(*xuanwuv1.VolumeModifyClaimList).ListMeta}
	for _, item := range obj.(*xuanwuv1.VolumeModifyClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeModifyClaims.
func (c *FakeVolumeModifyClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(volumemodifyclaimsResource, opts))
}

// Create takes the representation of a volumeModifyClaim and creates it.  Returns the server's representation of the volumeModifyClaim, and an error, if there is any.
func (c *FakeVolumeModifyClaims) Create(ctx context.Context, volumeModifyClaim *xuanwuv1.VolumeModifyClaim, opts v1.CreateOptions) (result *xuanwuv1.VolumeModifyClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(volumemodifyclaimsResource, volumeModifyClaim), &xuanwuv1.VolumeModifyClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.VolumeModifyClaim), err
}

// Update takes the representation of a volumeModifyClaim and updates it. Returns the server's representation of the volumeModifyClaim, and an error, if there is any.
func (c *FakeVolumeModifyClaims) Update(ctx context.Context, volumeModifyClaim *xuanwuv1.VolumeModifyClaim, opts v1.UpdateOptions) (result *xuanwuv1.VolumeModifyClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(volumemodifyclaimsResource, volumeModifyClaim), &xuanwuv1.VolumeModifyClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.VolumeModifyClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeModifyClaims) UpdateStatus(ctx context.Context, volumeModifyClaim *xuanwuv1.VolumeModifyClaim, opts v1.UpdateOptions) (*xuanwuv1.VolumeModifyClaim, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(volumemodifyclaimsResource, "status", volumeModifyClaim), &xuanwuv1.VolumeModifyClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.VolumeModifyClaim), err
}

// Delete takes name of the volumeModifyClaim and deletes it. Returns an error if one occurs.
func (c *FakeVolumeModifyClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(volumemodifyclaimsResource, name, opts), &xuanwuv1.VolumeModifyClaim{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeModifyClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(volumemodifyclaimsResource, listOpts)

	_, err := c.Fake.Invokes(action, &xuanwuv1.VolumeModifyClaimList{})
	return err
}

// Patch applies the patch and returns the patched volumeModifyClaim.
func (c *FakeVolumeModifyClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *xuanwuv1.VolumeModifyClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(volumemodifyclaimsResource, name, pt, data, subresources...), &xuanwuv1.VolumeModifyClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*xuanwuv1.VolumeModifyClaim), err
}
