/*
 Copyright (c) Huawei Technologies Co., Ltd. 2022-2023. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "huawei-csi-driver/client/apis/xuanwu/v1"
	"huawei-csi-driver/pkg/client/clientset/versioned/scheme"
	"net/http"

	rest "k8s.io/client-go/rest"
)

type XuanwuV1Interface interface {
	RESTClient() rest.Interface
	ResourceTopologiesGetter
	StorageBackendClaimsGetter
	StorageBackendContentsGetter
	VolumeModifyClaimsGetter
	VolumeModifyContentsGetter
}

// XuanwuV1Client is used to interact with features provided by the xuanwu.huawei.io group.
type XuanwuV1Client struct {
	restClient rest.Interface
}

func (c *XuanwuV1Client) ResourceTopologies() ResourceTopologyInterface {
	return newResourceTopologies(c)
}

func (c *XuanwuV1Client) StorageBackendClaims(namespace string) StorageBackendClaimInterface {
	return newStorageBackendClaims(c, namespace)
}

func (c *XuanwuV1Client) StorageBackendContents() StorageBackendContentInterface {
	return newStorageBackendContents(c)
}

func (c *XuanwuV1Client) VolumeModifyClaims() VolumeModifyClaimInterface {
	return newVolumeModifyClaims(c)
}

func (c *XuanwuV1Client) VolumeModifyContents() VolumeModifyContentInterface {
	return newVolumeModifyContents(c)
}

// NewForConfig creates a new XuanwuV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*XuanwuV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new XuanwuV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*XuanwuV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &XuanwuV1Client{client}, nil
}

// NewForConfigOrDie creates a new XuanwuV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *XuanwuV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new XuanwuV1Client for the given RESTClient.
func New(c rest.Interface) *XuanwuV1Client {
	return &XuanwuV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *XuanwuV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
